# Morphological operations

In [1]:
import cv2
import numpy as np

1. EROSION

In [2]:
img = cv2.imread(r"opencv_Images\Screenshot5.png")
img_resize = cv2.resize(img ,(700,600))
grey = cv2.

In [3]:
m = np.ones((5,7),np.int8)
print(m)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [4]:
er = cv2.erode(img_resize,m,iterations = 1)

2. Dilute

In [5]:
di = cv2.dilate(img_resize,m,iterations = 1)

In [6]:
cv2.imshow("image",img_resize)
cv2.imshow("eroded img",er)
cv2.imshow("dilated img",di)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [56]:
import cv2
import numpy as np

In [57]:
img = cv2.imread(r"opencv_Images\Screenshot43.png")
img = cv2.resize(img ,(500,600))
img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [71]:
kernal = np.ones((5,5),np.int8)
print(kernal)
kernal

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

3. Opening 

In [72]:
# morphologyEx(src, op, kernel[, dst[, anchor[, iterations[, borderType[, borderValue]]]]])

opening = cv2.morphologyEx(img , cv2.MORPH_OPEN , kernal , iterations =1)

4. Closing

In [73]:
# 

closing = cv2.morphologyEx(img , cv2.MORPH_CLOSE , kernal ,iterations =1)

5. Gradient

In [74]:
gradient = cv2.morphologyEx(img , cv2.MORPH_GRADIENT , kernal , iterations = 1)

6. Black Hat

In [75]:
black_hat = cv2.morphologyEx(img , cv2.MORPH_BLACKHAT , kernal , iterations =1)

7. Top Hat

In [76]:
top_hat =  cv2.morphologyEx(img , cv2.MORPH_TOPHAT , kernal , iterations =1)

In [77]:
cv2.imshow("gray image",img)
cv2.imshow("opening image",opening)
cv2.imshow("Closing image",closing)
cv2.imshow("Gradient image",gradient)
cv2.imshow("Black hat",black_hat)
cv2.imshow("Top Hat",top_hat)
cv2.waitKey(0)
cv2.destroyAllWindows()