# Create Blank Image

Black Image and White Image

In [5]:
import cv2
import numpy as np

In [1]:
img = cv2.imread(r"opencv_Images\Screenshot937.png")


NameError: name 'cv2' is not defined

In [7]:
print(img.shape)
print(img)

(437, 442, 3)
[[[31 31 31]
  [31 31 31]
  [31 31 31]
  ...
  [31 31 31]
  [31 31 31]
  [31 31 31]]

 [[25 25 25]
  [25 25 25]
  [25 25 25]
  ...
  [25 25 25]
  [ 0  0  0]
  [ 0  0  0]]

 [[25 25 25]
  [25 25 25]
  [25 25 25]
  ...
  [25 25 25]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[25 25 25]
  [25 25 25]
  [25 25 25]
  ...
  [25 25 25]
  [ 0  0  0]
  [ 0  0  0]]

 [[25 25 25]
  [25 25 25]
  [25 25 25]
  ...
  [25 25 25]
  [ 0  0  0]
  [ 0  0  0]]

 [[25 25 25]
  [25 25 25]
  [25 25 25]
  ...
  [25 25 25]
  [ 0  0  0]
  [ 0  0  0]]]


1. White Blank Image

In [10]:
new_img1 = np.ones((700,600,3),np.uint8)*255

In [11]:
print(new_img1.shape)
print(new_img1)

(700, 600, 3)
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


2. Black Blank Image

In [12]:
new_img2 = np.zeros((700,600,3),np.uint8)*255

In [13]:
print(new_img2.shape)
print(new_img2)

(700, 600, 3)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [14]:
cv2.imshow("White Blank Image",new_img1)
cv2.imshow("Black Blank Image",new_img2)
cv2.waitKey(0)
cv2.destroyAllWindows()