# HOUGH TRANSFORMATION LINES
lines on an image like sudoku..
1. y = mx + c
2. y = xsin& + xcos& --> polar form

In [2]:
import cv2
import numpy as np

1. Longest method represent a line.

In [13]:
img1 = cv2.imread(r"opencv_Images\lines.jpeg")
img1 = cv2.resize(img1,(500,500))

gry = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)

# edge
eg = cv2.Canny(gry,20,250)

lines = cv2.HoughLines(eg ,1 ,np.pi/180 , 200)
print(lines)
for r,th in lines[6]:
    a = np.cos(th)
    b = np.sin(th)

    x0 = a*r
    y0 = b*r

    x1 =  int(x0 + 1000 * (-b))
    y1 = int(y0 + 1000 * (-a))
    x2 =  int(x0 - 1000 * (-b))
    y2 = int(y0 - 1000 * (-a))

    cv2.line(img1,(x1,y1),(x2,y2),(0,255,0),2)
    

cv2.imshow("Image",img1)
# cv2.imshow("gray scale image",gry)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 10.          1.5707964]]

 [[489.          0.       ]]

 [[ 14.          1.5707964]]

 [[168.          1.5707964]]

 [[172.          1.5707964]]

 [[ 63.          0.       ]]

 [[224.          0.       ]]

 [[116.          1.5707964]]

 [[ 65.          0.       ]]

 [[116.          0.       ]]

 [[118.          0.       ]]

 [[222.          0.       ]]

 [[274.          0.       ]]

 [[276.          0.       ]]

 [[381.          0.       ]]

 [[383.          0.       ]]

 [[433.          0.       ]]

 [[435.          0.       ]]

 [[ 66.          1.5707964]]

 [[222.          1.5707964]]

 [[224.          1.5707964]]

 [[274.          1.5707964]]

 [[276.          1.5707964]]

 [[380.          1.5707964]]

 [[382.          1.5707964]]

 [[432.          1.5707964]]

 [[ 64.          1.5707964]]

 [[118.          1.5707964]]

 [[434.          1.5707964]]

 [[485.          1.5707964]]

 [[171.          0.       ]]

 [[485.          0.       ]]

 [[ 13.          0.       ]]

 [[330.   

##### 

2. Hough line transfer probability 

In [5]:
import cv2
import numpy as np

img = cv2.imread(r"opencv_Images\lines.jpeg")
img = cv2.resize(img,(500,500))
gr = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

eg = cv2.Canny(gr,20,250)

l = cv2.HoughLinesP(eg,1,np.pi/180 ,200,minLineLength = 180 , maxLineGap = 100)

for i in l:
    x1,y1,x2,y2 = i[0]
    cv2.line(img ,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()